files:
  include: juju-gui/**/*.scss
  exclude: juju-gui/static/gui/src/app/assets/css/plugins/**
options:
  formatter: stylish
  merge-default-rules: false
rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
  id-name-format:
    - 1
    - convention: hyphenatedbem
  nesting-depth: 0
  no-ids: 1
  no-vendor-prefixes: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 0
